-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 11:36:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NodeNote
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NodeNote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NodeNote` DEFAULT CHARACTER SET utf8 ;
USE `NodeNote` ;

-- -----------------------------------------------------
-- Table `NodeNote`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NodeNote`.`Items` ;

CREATE TABLE IF NOT EXISTS `NodeNote`.`Items` (
  `Item_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Completed` TINYINT(1) NOT NULL DEFAULT 0,
  `List_id` INT NOT NULL,
  PRIMARY KEY (`Item_id`),
  CONSTRAINT `List_id`
    FOREIGN KEY (`List_id`)
    REFERENCES `NodeNote`.`Lists` (`List_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `List_id_idx` ON `NodeNote`.`Items` (`List_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `NodeNote`.`Lists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NodeNote`.`Lists` ;

CREATE TABLE IF NOT EXISTS `NodeNote`.`Lists` (
  `List_id` INT NOT NULL AUTO_INCREMENT,
  `User_id` VARCHAR(32) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`List_id`),
  CONSTRAINT `User_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `NodeNote`.`Users` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `List_id_UNIQUE` ON `NodeNote`.`Lists` (`List_id` ASC) VISIBLE;

CREATE INDEX `User_id_idx` ON `NodeNote`.`Lists` (`User_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `NodeNote`.`UserLists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NodeNote`.`UserLists` ;

CREATE TABLE IF NOT EXISTS `NodeNote`.`UserLists` (
  `User_Id` VARCHAR(32) NOT NULL,
  `List_Id` INT NOT NULL,
  CONSTRAINT `User_Id`
    FOREIGN KEY (`User_Id`)
    REFERENCES `NodeNote`.`Users` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `List_Id`
    FOREIGN KEY (`List_Id`)
    REFERENCES `NodeNote`.`Lists` (`List_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `User_Id_idx` ON `NodeNote`.`UserLists` (`User_Id` ASC) VISIBLE;

CREATE INDEX `List_Id_idx` ON `NodeNote`.`UserLists` (`List_Id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `NodeNote`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NodeNote`.`Users` ;

CREATE TABLE IF NOT EXISTS `NodeNote`.`Users` (
  `User_id` VARCHAR(36) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `User_id_UNIQUE` ON `NodeNote`.`Users` (`User_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `NodeNote`.`Users` (`email` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
